- hosts: localhost
  tasks:
    - name: install go
      package:
        name: 
        - go
        - dep
      become: True

    - name: create workspace directory
      file:
        path: "{{ ansible_user_dir }}/go"
        state: directory

